name: plannerapp
description: A modern planning app built with Flutter
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Material icons
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  http: ^1.2.2
  flutter_local_notifications: ^17.2.1+2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


